config/routes.rb
Rails.application.routes.draw do
  resources :students

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
 belongs_to :class_room, optional: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :make_header, :make_link

  def make_header(title)
    "<h1>#{title}</h1>".html_safe
  end

  def make_link(text, path)
    if !path.is_a?(String)
      "<a href='#{path.class.to_s.downcase.pluralize}/#{path.id}'>#{text}</a>".html_safe
    else
      "<a href='#{path}'>#{text}</a>".html_safe
    end
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
    @student = Student.find_by(id: params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    Student.create(student_params)

    redirect_to students_path
  end

  # /students/:id/edit
  def edit
    @student = Student.find_by(id: params[:id])

  end


  def destroy
    @student = Student.find_by(id: params[:id])
    @student.destroy

    redirect_to students_path
  end


  private

  def student_params
    params.require(:student).permit(:name, :email, :dob)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentLister01</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_for student do  |f| %>
  <%= f.label(:name) %>
  <%= f.text_field(:name, class: 'input-group') %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :dob %>
  <%= f.date_field :dob %>

  <%= f.submit 'Create a cool student!' %>

<% end %>

app/views/students/edit.html.erb
<h1> Edit this Student </h1>

<%= render({partial: 'form', locals: {student: @student}}) %>

app/views/students/index.html.erb
<%= make_header 'All the Students!!!!' %>

<ul>
  <% @students.each do |student| %>
    <li><%= link_to student.name, student %></li>
  <% end %>
</ul>

<%= make_link 'Create a new student', new_student_path %>

app/views/students/new.html.erb
<h1>Create a New Student</h1>

<%= render({partial: 'form', locals: {student: @student}}) %>

app/views/students/show.html.erb
<h1>Student Show</h1>

<h2><%= @student.name %></h2>
<h4><%= @student.email %></h4>

<%= link_to 'Back', '/students' %>
<%= link_to('Edit this new student', edit_student_path(@student)) %>
<%= link_to 'Delete this new student', student_path(@student), method: 'DELETE' %>